name: Maven

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '24 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Run src
      env:
        SIMONW_TOKEN: ${{ secrets.UCALYPTUS_TOKEN }}
      run: |-
        cd src/
        sh run.sh
    - name: Run tests
      env:
        SIMONW_TOKEN: ${{ secrets.UCALYPTUS_TOKEN }}
      run: |-
        cd tests/
        sh runtest.sh        
